import { Toaster } from "@/components/ui/sonner"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import Link from "next/link"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex justify-center relative`}>
        <div className="max-w-screen-xl w-full">
          <div className="w-full h-16 p-4">
            <Link href={"/"}>
              <img src="/evercrow.png" className="h-12" />
            </Link>
          </div>
          {children}
        </div>
        <Toaster />
      </body>
    </html>
  )
}
